name: ai_resume_local

services:
  backend_cv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_cv_api
    # restart: unless-stopped
    env_file:
      - ./.env
    environment:
      IP_ADDRESS: ${IP_ADDRESS}
      WEB_PORT: ${WEB_PORT}
      WEB_ENV: ${WEB_ENV}
      # Kết nối đến các dịch vụ phụ trợ qua host.docker.internal (được expose bởi folder docker/) xem lai docker chua build duoc
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      AI_SERVICE_BASE_URL: ${AI_SERVICE_BASE_URL}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_S3_REGION: ${MINIO_S3_REGION}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_S3_BUCKET_CV: ${MINIO_S3_BUCKET_CV}
      MINIO_S3_BUCKET_LOGO: ${MINIO_S3_BUCKET_LOGO}
      MINIO_S3_BUCKET_AVATAR: ${MINIO_S3_BUCKET_AVATAR}
      MINIO_S3_BUCKET_BANNER: ${MINIO_S3_BUCKET_BANNER}
      MINIO_PATH_STYLE: ${MINIO_FORCE_PATH_STYLE}
      MINIO_FORCE_PATH_STYLE: ${MINIO_FORCE_PATH_STYLE}
      MINIO_PRESIGNED_URL_TTL: ${MINIO_PRESIGNED_URL_TTL}
    ports:
      - '${WEB_PORT}:${WEB_PORT}'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
