export const CACHE_KEYS = {
  JOB_LIST: 'job:list',
  JOB_DETAIL: 'job:detail',
  ADMIN_ANALYTICS_OVERVIEW: 'admin-analytics:overview',
  ADMIN_ANALYTICS_USER_GROWTH: 'admin-analytics:user-growth',
  ADMIN_ANALYTICS_JOB_GROWTH: 'admin-analytics:job-growth',
  ADMIN_ANALYTICS_APPLICATION_GROWTH: 'admin-analytics:application-growth',
  ADMIN_ANALYTICS_RECENT_ACTIVITIES: 'admin-analytics:recent-activities',
  SKILL_LIST: 'skill:list',
  SKILL_DETAIL: 'skill:detail',
  COMPANY_LIST: 'company:list',
  COMPANY_DETAIL: 'company:detail',
  CV_LIST: 'cv:list',
  CV_DETAIL: 'cv:detail',
  JOB_APPLICATION_LIST: 'job-application:list',
  JOB_APPLICATION_DETAIL: 'job-application:detail',
  USER_LIST: 'user:list',
  USER_DETAIL: 'user:profile',
  CAREER_CATEGORY_LIST: 'career-category:list',
  CAREER_CATEGORY_DETAIL: 'career-category:detail',
  CAREER_CATEGORY_TOP: 'career-category:top',
} as const;

export const CACHE_VERSION_KEYS = {
  JOB_LIST: 'job:list',
  JOB_DETAIL: 'job:detail',
  ADMIN_ANALYTICS_OVERVIEW: 'admin-analytics:overview',
  ADMIN_ANALYTICS_USER_GROWTH: 'admin-analytics:user-growth',
  ADMIN_ANALYTICS_JOB_GROWTH: 'admin-analytics:job-growth',
  ADMIN_ANALYTICS_APPLICATION_GROWTH: 'admin-analytics:application-growth',
  ADMIN_ANALYTICS_RECENT_ACTIVITIES: 'admin-analytics:recent-activities',
  SKILL_LIST: 'skill:list',
  SKILL_DETAIL: 'skill:detail',
  COMPANY_LIST: 'company:list',
  COMPANY_DETAIL: 'company:detail',
  CV_LIST: 'cv:list',
  CV_DETAIL: 'cv:detail',
  JOB_APPLICATION_LIST: 'job-application:list',
  JOB_APPLICATION_DETAIL: 'job-application:detail',
  USER_LIST: 'user:list',
  USER_DETAIL: 'user:profile',
  CAREER_CATEGORY_LIST: 'career-category:list',
  CAREER_CATEGORY_DETAIL: 'career-category:detail',
  CAREER_CATEGORY_TOP: 'career-category:top',
} as const;

export const CACHE_TTL = {
  LIST: 600,
  DETAIL: 1800,
  DEGRADED: 60,
  JOB_APPLICATION_LIST: 30,
  JOB_APPLICATION_DETAIL: 60,
} as const;
